#!/bin/bash

#TODO: Documentation

progname="PGP-Backup"
libname="Decryption"
version="v0.2.0-alpha.3"

# ARG_OPTIONAL_BOOLEAN([unpack],[u],[Unpacks all archives from pgpbackup-encrypt])
# ARG_HELP([short program description (optional)],[long program description (optional)])
# ARG_VERSION([echo $version])
# ARGBASH_GO()

# [ <-- needed because of Argbash
function urldecode {
    : "${*//+/ }"
    echo -e "${_//%/\\x}"
}

function decrypt {
    local path=$1

    find "$path" -maxdepth 1 -type f -iname "*.gpg" | while read j
    do
        cd "../tmp"
        origFileName=$(gpg -q --status-fd 1 --use-embedded-filename "../backup/$j" | grep -E '^\[GNUPG:\] PLAINTEXT 62 [[:digit:]]+ .*$' | cut -f 5 -d " ")
        origFileName=$(urldecode "$origFileName")
        origFile="$(dirname "$j")/$origFileName"
        mv "$origFileName" "../decrypted/$origFile"
        if [ "$_arg_unpack" = "on" ] && [[ $origFile = *.pb.zip ]]; then
            cd "../decrypted"
            folderName=${origFile::-7}
            if [[ "$origFile" = *backup.zip ]]; then
                origFile="."
            fi
            unzip -q "$origFile" -d "$folderName"
            rm "$origFile"
        elif [ "$_arg_unpack" = "off" ] && [[ $origFile = *.pb.zip ]]; then
            cd "../decrypted"
            folderName=${origFile::-7}
            mv "$origFile" "$folderName.zip"
        fi
        cd "../backup"
    done

    find "$path" -mindepth 1 -maxdepth 1 -type d | while read j
    do
        decrypt "$j"
    done
}

echo $progname $version "-" $libname

mkdir "../tmp"
mkdir "../decrypted"

find . -depth ! -path . -type d | while read i
do
    mkdir -p "../decrypted/$i"
done

decrypt "."

# Restore folder names
cd "../decrypted"
find "." -mindepth 1 -depth -type d | while read j
do
    path=$(dirname "$j")
    hashedName=$(basename "$j")
    pattern="^${hashedName};.*$"
    if [ -f "$path/foldernames.txt" ]; then
        name=$(grep -E "$pattern" "$path/foldernames.txt" | cut -f 2 -d ";")
        if [ "$name" != "" ]; then
            mv "$j" "$path/$name"
        fi
    fi
done

find "." -type f -iname "foldernames.txt" | while read j
do
    rm "$j"
done

# Copy decrypt stuff to decrypted folder
cp "../backup/decrypt.sh" "decrypt.sh"
cp "../backup/pgpbackup-decrypt" "pgpbackup-decrypt" > /dev/null

# Tidy up
rm -r "../tmp"

echo "Finished decrypting!"
exit 0
# ] <-- needed because of Argbash
